CronJob
A CronJob starts one-time Jobs on a repeating schedule.
CronJob is meant for performing regular scheduled actions such as backups, report generation, and so on. 
One CronJob object is like one line of a crontab (cron table) file on a Unix system. 
It runs a Job periodically on a given schedule, written in Cron format.

apiVersion: batch/v1
kind: CronJob
metadata:
   name: hellojob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
   spec:
    template:
      metadata:
         labels:
           app: hello
      spec:
        containers:
          - name: hello
            image: busybox
            command: ["echo","hello,k8s"]
        restartPolicy: Never