StatefulSets
A StatefulSet runs a group of Pods, and maintains a sticky identity for each of those Pods. 
This is useful for managing applications that need persistent storage or a stable, unique network identity.

StatefulSet.YAMl

apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: db
spec:
   replicas: 3
   selector:
       matchLabels:
            app: mydb
   serviceName: "dbservice"
   template:
     metadata:
         labels:
            app: mydb
     spec:
        containers:
          - name: mydbcontainer
            image: mysql
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                   configMapKeyRef:
                       name: mysql-config
                       key: mysql-password
            ports:
              - containerPort: 3306
   volumeClaimTemplates:
         - metadata:
             name: dbb
           spec:
             accessModes: ["ReadWriteMany"]
             resources:
                requests:
                   storage: 1Gi
                limits:
                  storage: 1Gi