apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeployment
spec:
  replicas: 3
  strategy:
     type: RollingUpdate
     rollingUpdate:
         maxSurge: 2
         maxUnavailable: 0
  selector:
   matchLabels:
      env: dev
  template:
       metadata:
          labels:
              env: dev
       spec:
            containers:
                 - name: nginxcontaine
                   image: nginx
                   ports:
                     - containerPort: 80
                   volumeMounts:
                    - mountPath: "/usr/share/nginx/html"
                      name: myvolume

            volumes:
               -  name: myvolume
                  nfs:
                     server: fs-0bc49cff53cfa9704.efs.us-east-2.amazonaws.com
                     path: /test